/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package areas;

import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import calculos.CalculosArea;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import static java.lang.Double.parseDouble;
import java.text.DecimalFormat;

/**
 *
 * @author anthoni
 */
public class CalcularAreas extends javax.swing.JFrame {
    int x,y;
    CalculosArea CA = new CalculosArea();
    DecimalFormat df = new DecimalFormat("#.00");
    public CalcularAreas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TextBase = new javax.swing.JTextField();
        TextAltura = new javax.swing.JTextField();
        resultadoTri = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textLado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resultadoCua = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextLadoA = new javax.swing.JTextField();
        TextLadoB = new javax.swing.JTextField();
        resultadoRec = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextRadio = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        resultadoCir = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jInternalFrame4.setBackground(new java.awt.Color(62, 70, 89));
        jInternalFrame4.setBorder(null);
        jInternalFrame4.setForeground(new java.awt.Color(62, 70, 89));
        jInternalFrame4.setVisible(true);
        jInternalFrame4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel11.setText("Área del Triángulo");
        jInternalFrame4.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 220, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AreaTriangulo.png"))); // NOI18N
        jInternalFrame4.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 180, 180));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel13.setText("b:");
        jInternalFrame4.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel14.setText("h:");
        jInternalFrame4.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        TextBase.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextBase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextBaseKeyTyped(evt);
            }
        });
        jInternalFrame4.getContentPane().add(TextBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 90, -1));

        TextAltura.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextAlturaKeyTyped(evt);
            }
        });
        jInternalFrame4.getContentPane().add(TextAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 90, -1));

        resultadoTri.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        resultadoTri.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInternalFrame4.getContentPane().add(resultadoTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 170, 50));

        jButton11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(51, 51, 51));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calcular.png"))); // NOI18N
        jButton11.setText("Calcular");
        jButton11.setBorder(null);
        jButton11.setFocusPainted(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalcularClick.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jButton14.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(51, 51, 51));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        jButton14.setText("Limpiar");
        jButton14.setBorder(null);
        jButton14.setFocusPainted(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LimpiarClick.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jButton4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CerrarClick.png"))); // NOI18N
        jButton4.setText("Salir");
        jButton4.setBorder(null);
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        getContentPane().add(jInternalFrame4);
        jInternalFrame4.setBounds(760, 20, 350, 520);

        jInternalFrame1.setBackground(new java.awt.Color(62, 70, 89));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Área del Cuadrado");
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 210, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AreaCuadrado.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 180, 180));

        textLado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textLado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textLado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLadoActionPerformed(evt);
            }
        });
        textLado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textLadoKeyTyped(evt);
            }
        });
        jInternalFrame1.getContentPane().add(textLado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 90, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setText("a=");
        jInternalFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        resultadoCua.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        resultadoCua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInternalFrame1.getContentPane().add(resultadoCua, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 170, 50));

        jButton10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calcular.png"))); // NOI18N
        jButton10.setText("Calcular");
        jButton10.setBorder(null);
        jButton10.setFocusPainted(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalcularClick.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jButton13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(51, 51, 51));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        jButton13.setText("Limpiar");
        jButton13.setBorder(null);
        jButton13.setFocusPainted(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LimpiarClick.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jButton3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CerrarClick.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.setBorder(null);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(390, 20, 350, 520);

        jInternalFrame2.setBackground(new java.awt.Color(62, 70, 89));
        jInternalFrame2.setForeground(new java.awt.Color(62, 70, 89));
        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setText("Área del Rectángulo");
        jInternalFrame2.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 240, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AreaRectangulo.png"))); // NOI18N
        jInternalFrame2.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 180, 180));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setText("a=");
        jInternalFrame2.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel7.setText("b=");
        jInternalFrame2.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        TextLadoA.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextLadoA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextLadoA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextLadoAKeyTyped(evt);
            }
        });
        jInternalFrame2.getContentPane().add(TextLadoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 90, -1));

        TextLadoB.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextLadoB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextLadoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextLadoBKeyTyped(evt);
            }
        });
        jInternalFrame2.getContentPane().add(TextLadoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 90, -1));

        resultadoRec.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        resultadoRec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInternalFrame2.getContentPane().add(resultadoRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 170, 50));

        jButton9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 51, 51));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calcular.png"))); // NOI18N
        jButton9.setText("Calcular");
        jButton9.setBorder(null);
        jButton9.setFocusPainted(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalcularClick.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jButton12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 51, 51));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        jButton12.setText("Limpiar");
        jButton12.setBorder(null);
        jButton12.setFocusPainted(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LimpiarClick.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CerrarClick.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        getContentPane().add(jInternalFrame2);
        jInternalFrame2.setBounds(1130, 20, 350, 520);

        jInternalFrame3.setBackground(new java.awt.Color(62, 70, 89));
        jInternalFrame3.setForeground(new java.awt.Color(62, 70, 89));
        jInternalFrame3.setVisible(true);
        jInternalFrame3.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel8.setText("Área del CÍrculo");
        jInternalFrame3.getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 0, 180, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AreaCirculo.png"))); // NOI18N
        jInternalFrame3.getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 80, 180, 180);

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel10.setText("r:");
        jInternalFrame3.getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 290, 20, 30);

        TextRadio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextRadio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextRadio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextRadioKeyTyped(evt);
            }
        });
        jInternalFrame3.getContentPane().add(TextRadio);
        TextRadio.setBounds(130, 290, 90, 30);

        jButton5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calcular.png"))); // NOI18N
        jButton5.setText("Calcular");
        jButton5.setBorder(null);
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalcularClick.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton5);
        jButton5.setBounds(120, 350, 100, 40);

        jButton6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Limpiar.png"))); // NOI18N
        jButton6.setText("Limpiar");
        jButton6.setBorder(null);
        jButton6.setFocusPainted(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LimpiarClick.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton6);
        jButton6.setBounds(20, 350, 100, 40);

        resultadoCir.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        resultadoCir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInternalFrame3.getContentPane().add(resultadoCir);
        resultadoCir.setBounds(90, 410, 170, 50);

        jButton2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CerrarClick.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.setBorder(null);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerrar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton2);
        jButton2.setBounds(220, 350, 100, 40);

        getContentPane().add(jInternalFrame3);
        jInternalFrame3.setBounds(20, 20, 350, 520);

        jMenu1.setText("AREAS");

        jMenuItem1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jMenuItem1.setText("Cuadrado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jMenuItem2.setText("Rectangulo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jMenuItem3.setText("Circulo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jMenuItem4.setText("Triangulo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1479, 603));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jInternalFrame1.setVisible(true);
        jInternalFrame2.setVisible(false);
        jInternalFrame3.setVisible(false);
        jInternalFrame4.setVisible(false);
        TamañoColor(jInternalFrame1);
        this.getContentPane().setBackground(Color.orange);
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jInternalFrame1.setVisible(false);
        jInternalFrame2.setVisible(false);
        jInternalFrame3.setVisible(false);
        jInternalFrame4.setVisible(false);
        this.setSize(new Dimension(350, 550));
//        jMenu4.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jInternalFrame1.setVisible(false);
        jInternalFrame2.setVisible(false);
        jInternalFrame3.setVisible(true);
        jInternalFrame4.setVisible(false);
        TamañoColor(jInternalFrame3);
        this.getContentPane().setBackground(Color.red);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jInternalFrame1.setVisible(false);
        jInternalFrame2.setVisible(false);
        jInternalFrame3.setVisible(false);
        jInternalFrame4.setVisible(true);
        TamañoColor(jInternalFrame4);
        this.getContentPane().setBackground(Color.blue);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jInternalFrame1.setVisible(false);
        jInternalFrame2.setVisible(true);
        jInternalFrame3.setVisible(false);
        jInternalFrame4.setVisible(false);
        TamañoColor(jInternalFrame2);
        this.getContentPane().setBackground(Color.yellow);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        double num1;
        String resultado;
        num1 = parseDouble(TextRadio.getText());
        resultado = String.valueOf(df.format(CA.AreaCirculo(num1)));
        resultadoCir.setText(resultado);
        jButton5.setForeground(Color.decode("#ffff"));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        resultadoCir.setText("");
        TextRadio.setText("");
        jButton6.setForeground(Color.decode("#ffff"));
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void textLadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLadoActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        double num1,num2;
        String resultado;
        num1 = parseDouble(TextLadoA.getText());
        num2 = parseDouble(TextLadoB.getText());
        resultado = String.valueOf(df.format(CA.AreaRectangulo(num1, num2)));
        resultadoRec.setText(resultado);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         double num1;
        String resultado;
        num1 = parseDouble(textLado.getText());
        resultado = String.valueOf(df.format(CA.AreaCuadrado(num1)));
        resultadoCua.setText(resultado);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       double num1,num2;
        String resultado;
        num1 = parseDouble(TextBase.getText());
        num2 = parseDouble(TextAltura.getText());
        resultado = String.valueOf(df.format(CA.AreaTriangulo(num1, num2)));
        resultadoTri.setText(resultado);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        resultadoCua.setText("");
        TextLadoA.setText("");
        TextLadoB.setText("");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        resultadoCua.setText("");
        textLado.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        resultadoTri.setText("");
        TextAltura.setText("");
        TextBase.setText("");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jInternalFrame4.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jInternalFrame3.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jInternalFrame1.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jInternalFrame2.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void TextRadioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextRadioKeyTyped
        
        char c=evt.getKeyChar();
 
 
	if(Character.isLetter(c)) {
		getToolkit().beep();
 
		evt.consume();
        }   
    }//GEN-LAST:event_TextRadioKeyTyped

    private void textLadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textLadoKeyTyped
        char c=evt.getKeyChar();
 
 
	if(Character.isLetter(c)) {
		getToolkit().beep();
 
		evt.consume();
        }   
    }//GEN-LAST:event_textLadoKeyTyped

    private void TextBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextBaseKeyTyped
        char c=evt.getKeyChar();
 
 
	if(Character.isLetter(c)) {
		getToolkit().beep();
 
		evt.consume();
        }   
    }//GEN-LAST:event_TextBaseKeyTyped

    private void TextAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextAlturaKeyTyped
       char c=evt.getKeyChar();
 
 
	if(Character.isLetter(c)) {
		getToolkit().beep();
 
		evt.consume();
        }   
    }//GEN-LAST:event_TextAlturaKeyTyped

    private void TextLadoAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextLadoAKeyTyped
        char c=evt.getKeyChar();
 
 
	if(Character.isLetter(c)) {
		getToolkit().beep();
 
		evt.consume();
        }   
    }//GEN-LAST:event_TextLadoAKeyTyped

    private void TextLadoBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextLadoBKeyTyped
        char c=evt.getKeyChar();
 
 
	if(Character.isLetter(c)) {
		getToolkit().beep();
 
		evt.consume();
        }   
    }//GEN-LAST:event_TextLadoBKeyTyped

  
    
    private void TamañoColor(JInternalFrame jInternalFrame){
        jInternalFrame.setSize(350, 520);
        jInternalFrame.setUI(null);
        jInternalFrame.setLocation(0, -20);
        jInternalFrame.getContentPane().setBackground( Color.decode("#3E4659") );
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularAreas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextAltura;
    private javax.swing.JTextField TextBase;
    private javax.swing.JTextField TextLadoA;
    private javax.swing.JTextField TextLadoB;
    private javax.swing.JTextField TextRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField resultadoCir;
    private javax.swing.JTextField resultadoCua;
    private javax.swing.JTextField resultadoRec;
    private javax.swing.JTextField resultadoTri;
    private javax.swing.JTextField textLado;
    // End of variables declaration//GEN-END:variables
}
